export const outletPayload = {
    update: {
        name: "",
        phone: "",
        date: "",
        address: "",
        time: "",
        promotion: "",
        promo_description: "",
    },
    store: {
        name: "",
        phone: "",
        date: "",
        address: "",
        time: "",
        promotion: "",
        promo_description: "",
    },
    columns: [
        { id: "name", label: "Name", minWidth: 250 },
        { id: "phone", label: "Phone", minWidth: 150 },
        { id: "date", label: "Date", minWidth: 150 },
        { id: "address", label: "Address", minWidth: 250 },
        { id: "time", label: "Time", minWidth: 150 },
        { id: "promotion", label: "Promotion", minWidth: 250 },
        { id: "Promo_description", label: "Promo_description", minWidth: 250 },
    ],
    paginateParams: {
        page: 1,
        per_page: 10,
        columns: "name",
        search: "",
        order: "id",
        sort: "DESC",
        value: "",
        start_date: "",
        end_date: "",
    },
};
